version: '3'

services:
    zeppelin:
        hostname: zeppelin
        container_name: zeppelin
        build: .
        depends_on:
            - neo4j-algo
            - neo4j-gdn
        ports:
            - 8080:8080
        volumes:
        - ./zeppelin/notebook:/zeppelin/notebook
        - ./zeppelin/conf:/zeppelin/conf
        - ./zeppelin/data:/zeppelin/spark-warehouse
        environment:
            - PYSPARK_PYTHON=python3
#            - ZEPPELIN_NOTEBOOK_HOMESCREEN=2EYYCADG3
#            - ZEPPELIN_NOTEBOOK_HOMESCREEN_HIDE=true
    neo4j-algo:
        hostname: neo4j-algo
        container_name: neo4j-algo
        image: neo4j:3.5
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/zeppelin
            - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*, algo.*
    neo4j-gdn:
        hostname: neo4j-gdn
        container_name: neo4j-gdn
        image: neo4j:3.5
        ports:
            - 7475:7474
            - 7688:7687
        volumes:
            - ./neo4j/data:/data
            - ./neo4j/plugins:/plugins
        environment:
            - NEO4J_AUTH=neo4j/zeppelin
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*, gds.*





