version: '3'

services:
    zeppelin:
        hostname: zeppelin
        container_name: zeppelin
        build: .
        depends_on:
            - neo4j
        ports:
            - 8080:8080
        volumes:
        - ./zeppelin/notebook:/zeppelin/notebook
        - ./zeppelin/conf:/zeppelin/conf
        - ./zeppelin/data:/zeppelin/spark-warehouse
        environment:
            - PYSPARK_PYTHON=python3
            - ZEPPELIN_NOTEBOOK_HOMESCREEN=2EYYCADG3
            - ZEPPELIN_NOTEBOOK_HOMESCREEN_HIDE=true
    neo4j:
        hostname: neo4j
        container_name: neo4j
        image: neo4j:3.5
        ports:
            - 7474:7474
            - 7687:7687
        environment:
            - NEO4J_AUTH=neo4j/zeppelin
            - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*, algo.*